### ISSUE TITLE
problem with the data

### ISSUE THREAD

**Issue by slz929** [valeriopaolicelli/adageo-WACV2021#1]
Thansk for fantanstic works!
I wonder why the SVOX from google drive is not the same as the data details listed in the repo? and I try to fix the training command you have mentioned, but the training stops after 3 epochs because of the worse recall. How can I fix that ?
![image](https://user-images.githubusercontent.com/17669514/141069152-a6106d16-ac34-45f5-8dc9-446d7571e772.png)

**Comment by valeriopaolicelli** [comment]
Hi, sorry for the late reply.
thanks for interest in this work. The images in GDrive folder are only related to SVOX and they don't include the pseudo-target dataset which should be generated during **Phase1** of our framework. 
Unfortunately, we didn't release yet the phase1 code since it would take a lot of effort to make it "releaseable". Overall you can easily use the available repositories of BIOST and replicate our pipeline.

**Comment by gmberton** [comment]
Hello, if you want to train with AdAGeo you first need to create the pseudo-target dataset using the domain adaptive data augmentation method, aka BiOST (https://github.com/tomercohen11/BiOST)
In a few weeks we will release the code to compute the pseudo-target with another method, to simplify the training.
